name: linux

on:
  workflow_dispatch:

jobs:
  ubuntu1804:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [ 3.8.5 ]

    env:
      ONNX_VERSION: v1.11.1
      SHARED_PKG_NAME: onnxruntime-1.11.1-ubuntu1804-shared
      STATIC_PKG_NAME: onnxruntime-1.11.1-ubuntu1804-static

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 配置Python环境 onnxruntime要求python minor version: expecting python 3.6+
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # 检出onnxruntime
      - name: checkout onnxruntime
        uses: actions/checkout@v2
        with:
          repository: microsoft/onnxruntime
          path: onnxruntime-${{ env.ONNX_VERSION }}
          ref: ${{ env.ONNX_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-onnxruntime.sh onnxruntime-${{ env.ONNX_VERSION }}
          cp onnxruntime_cmake_options.txt onnxruntime-${{ env.ONNX_VERSION }}

      # 编译
      - name: build
        with:
          arch: aarch64
          distro: ubuntu18.04      
          run: |
            cd onnxruntime-${{ env.ONNX_VERSION }}
            chmod a+x build-onnxruntime.sh &&./build-onnxruntime.sh

      # install文件夹改名linux，并使用7z压缩
      - name: 7zip
        run: |
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Release/install linux
          7z a ${{ env.SHARED_PKG_NAME }}.7z linux
          rm -r -f linux
          mv onnxruntime-${{ env.ONNX_VERSION }}/build/Linux/Release/install-static linux
          7z a ${{ env.STATIC_PKG_NAME }}.7z linux
          rm -r -f linux

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SHARED_PKG_NAME }}
          path: ${{ env.SHARED_PKG_NAME }}.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.STATIC_PKG_NAME }}
          path: ${{ env.STATIC_PKG_NAME }}.7z
